### PR TITLE
remove note as rack PR merged

### PR DESCRIPTION
**Pull request by go2null**
Rack [PR 1181](https://github.com/rack/rack/pull/1181) merged 20 days ago.

### CODE REVIEW

**Comment by ioquatix** [comment]
Unfortunately we still need rack to make a release with this code.

**Comment by go2null** [comment]
as a note, last release was https://github.com/rack/rack/tree/2.0.7 and that didn't have this patch.
So, check again when https://github.com/rack/rack/tree/2.0.8 is live.

**Comment by parndt** [comment]
Rack v2.0.8 was released December 18, 2019

**Comment by ioquatix** [comment]
Can you please rebase on master.

**Comment by ioquatix** [comment]
This has been updated, thanks for your PR.

**Pull request closed without merging**
