### PR TITLE
Reformat the code to make it github-readable

### PR DESCRIPTION
**Pull request by llaine**

### CODE REVIEW

**Comment by ioquatix** [comment]
Perhaps we should fix github rather than modify code.

**Comment by tarcieri** [comment]
As I've said before, in a language where almost everyone in the world uses two space indentation, your code looks weird.

**Comment by ioquatix** [comment]
I've had that argument before and so far it hasn't held water. Good developers can deal with indentation.

Call my code looking weird, is pretty insulting.

**Comment by tarcieri** [comment]
There's pretty universal agreement among Rubyists as to what indentation style to use:

https://ukupat.github.io/tabs-or-spaces/

Rubyists use 2 spaces

All I'm trying to point out is that by diverging this, you're risking putting people off from your project.

**Comment by ioquatix** [comment]
I'm hoping to make a dent in that pie chart :D

**Comment by ioquatix** [comment]
Actually, just on the off hand, I did read/think about one argument about tabs/spaces that made me think that spaces have some value - tabs in unix are 8 wide - especially in older hardware. We also see this on github (despite them having `tab-size` in CSS) and a few other places. But, just for a moment, I was thinking - if you were using grep or some other unix tool, spaces mean the code always looks the same in terminals, text editors - it's not just about text editors in this case. A very minor advantage, but one I thought about none the less.

**Comment by ioquatix** [comment]
I'll think about this but it's unlikely I'm going to change my whitespace policy across 200 repositories.

**Comment by llaine** [comment]
Just put this .editorconfig file in your 200 repos and you won't notice the difference :smile: 

```
# EditorConfig is awesome: http://EditorConfig.org

# top-most EditorConfig file
root = true

# Unix-style newlines with a newline ending every file
[*]
indent_style = space
```

**Comment by ioquatix** [comment]
I tried using `.editorconfig` - it's an interesting solution but I think it solves the wrong problem.

The point of using tabs is that users can choose the indentation width they prefer - it's liberating for users. I personally have my laptop and desktop set to use different size tabs because they have different screen configurations.

But, using `.editorconfig` with `indent_style = tab` and a fixed tab width is like the anti-thesis of this liberation - the entire point is that if I'm a user of github, I should be able to set the tab width I prefer, not what is set in `.editorconfig`. Simply setting `.editorconfig` to use hard tabs with width 2 doesn't work for me either - because then on my desktop, tabs are forced to size 2 but I prefer 4 there.

**Comment by ioquatix** [comment]
It would make more sense for users to have a `~/.editorconfig` that works for all projects, and then I can have one file on my laptop and one file on my desktop, and everything would just work.

**Pull request closed without merging**
