### PR TITLE
rack: return generic error instead of leaking exception msg

### LINKED ISSUE #98: Option to avoid leaking exception messages in the response body
When the application raises an exception, Falcon returns the message of the exception in the response body. I think it would be great to introduce a flag to disable this. In development environments seeing the exception message can be helpful. However, in a production environment, we might want to show a generic error message instead.

Puma has an option to do this: https://github.com/puma/puma/blob/6baa4d8e1c88f2e4db2918df48416a5c49feec40/lib/puma/server.rb#L919

Is there a way to do this in Falcon? I have not found anything in the docs. If there isn't a way to do this, @ioquatix would you be open to introduce this feature? I'm happy to help.

### PR DESCRIPTION
**Pull request by davidor**
Fixes #98

### CODE REVIEW

**Comment by ioquatix** [comment]
Why not use a middleware to do this, if that's your desire?

**Comment by davidor** [comment]
Thanks for the quick response @ioquatix 

I can use a middleware to do this, but I thought that it might make more sense to change this to avoid leaking sensitive information.

**Comment by gottlike** [comment]
This kind of relates to: https://github.com/socketry/falcon/issues/112

Would love to see this PR merged :)

**Comment by davidor** [comment]
@ioquatix sorry, I forgot about this PR and deleted my fork some time ago. Now I can't edit this PR, so I had to open a new one. It's the same commit but rebased on master: https://github.com/socketry/falcon/pull/130

**Pull request closed without merging**
